name: Build and Deploy Romer

on:
  push:
    branches:
      - Romer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace API_KEY in index.html
        run: |
          sed -i 's/\${API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g' index.html

      - name: (Optional) Build project
        run: echo "Build goes here"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.1.4
        with:
          branch: gh-pages # Гілка, куди буде деплой
          folder: .         # Каталог, який ти деплоїш (тут корінь репозиторію)
          token: ${{ secrets.GITHUB_TOKEN }}
