name: Build Romer

on:
  push:
    branches:
      - Romer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace API_KEY in index.html
        run: |
          sed -i 's/\${API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g' index.html

      - name: (Optional) Build project
        run: echo "Build goes here"

      - name: (Optional) Deploy
        run: echo "Deploy step here"
